ALTER TABLE stores ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS business_hours VARCHAR(200);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS one_liner VARCHAR(200);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS target_customers TEXT[];
ALTER TABLE stores ADD COLUMN IF NOT EXISTS photos TEXT[];
ALTER TABLE stores ADD COLUMN IF NOT EXISTS naver_place_url VARCHAR(500);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS naver_rating DECIMAL(2,1);
